name: Archive Myrient Links
on: 
  workflow_dispatch:

jobs:
  archive_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Libs
        run: pip install requests beautifulsoup4 tqdm

      - name: Start Scraping
        run: python scraper.py

      - name: Upload Final Backup
        uses: actions/upload-artifact@v4
        with:
          name: Xbox-Links-Archive
          path: Xbox_Full_Backup.zip
          retention-days: 5
